server/config/routes.rb
Rails.application.routes.draw do
  resources :paretos

  resources :data_points, only: [:index] do
    get :status, on: :collection
  end

  resources :analyses, only: [:index] do
    get :status, on: :collection
  end

  resources :compute_nodes

  resources :projects, shallow: true do
    member do
      get :status
    end

    resources :analyses, shallow: true do
      member do
        post :action
        post :upload
        get :stop
        get :status
        get :page_data
        get :analysis_data
        get :download_status
        get :debug_log
        get :new_view
        get :plot_parallelcoordinates
        post :plot_parallelcoordinates
        get :plot_scatter
        get :plot_radar
        get :plot_bar
        get :download_data
        get :download_analysis_zip
        get :download_algorithm_results_zip
        get :dencity

        get :plot_xy_interactive
        post :plot_xy_interactive
      end

      collection do
        get :status
      end

      resources :measures, only: [:show, :index], shallow: true
      resources :paretos, only: [:show, :index, :edit, :update], shallow: true
      resources :variables, only: [:show, :index, :edit, :update], shallow: true do
        collection do
          get :download_metadata
          get :download_variables
          get :metadata

          get :modify
          post :modify
        end
      end

      resources :data_points, shallow: true do
        member do
          get :view_report
          # get :download_reports # TODO: Remove this
          get :dencity

          # Download reports
          post :download_report

          # TODO: Review the end points
          put :run
          post :upload_file
          delete :result_files
        end

        collection do
          post :batch_upload
        end
      end
    end
    # end
  end

  resources :admin, only: [:index] do
    collection do
      get :backup_database
      post :restore_database
    end
  end

  match '/about', to: 'pages#about', via: :get
  match '/status', to: 'pages#status', via: :get

  root to: 'pages#dashboard'
end

server/app/views/pages/about.html.erb
<%
#*******************************************************************************
# OpenStudio(R), Copyright (c) 2008-2016, Alliance for Sustainable Energy, LLC.
# All rights reserved.
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# (1) Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# (2) Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# (3) Neither the name of the copyright holder nor the names of any contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission from the respective party.
#
# (4) Other than as required in clauses (1) and (2), distributions in any form
# of modifications or other derivative works may not use the "OpenStudio"
# trademark, "OS", "os", or any other confusingly similar designation without
# specific prior written permission from Alliance for Sustainable Energy, LLC.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER, THE UNITED STATES
# GOVERNMENT, OR ANY CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#*******************************************************************************
%>

<h2>About</h2>

<div class="row-fluid">
  <div class="span4">
    <br/>
    <p>
      OpenStudio Server is a framework that enables measure-based analyses of OpenStudio models on the cloud.
      This framework takes advantage of parallel computing to run analyses such as sampling, calibration, and optimization.
      The OpenStudio Cloud Management Console allows users to manage analysis runs and visualize results through a variety of charts.
    </p>

    <p>
      OpenStudio Server is implemented in Ruby and uses R for statistical computations as well as dispatching runs to OpenStudio and EnergyPlus.
      Resulting data is then stored in a Mongo database and can be visualized in the Ruby on Rails web application.
    </p>

    <p>
      Before running analyses on the OpenStudio Server framework, an OpenStudio model must first be created via the <%=link_to "OpenStudio client application suite", "http://openstudio.nrel.gov" %>.
      The Parametric Analysis Tool (PAT) interface is then used to find and download BCL measures to be applied to the model.
      This information is then exported to a spreadsheet format and the cloud analysis can then be run, as shown in the figure on the right.
    </p>

  </div>
  <div class="span8">
    <%= image_tag("framework.png", :size => "700x464") %>
  </div>


</div>

server/app/views/pages/dashboard.html.erb
<%
#*******************************************************************************
# OpenStudio(R), Copyright (c) 2008-2016, Alliance for Sustainable Energy, LLC.
# All rights reserved.
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# (1) Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# (2) Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# (3) Neither the name of the copyright holder nor the names of any contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission from the respective party.
#
# (4) Other than as required in clauses (1) and (2), distributions in any form
# of modifications or other derivative works may not use the "OpenStudio"
# trademark, "OS", "os", or any other confusingly similar designation without
# specific prior written permission from Alliance for Sustainable Energy, LLC.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER, THE UNITED STATES
# GOVERNMENT, OR ANY CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#*******************************************************************************
%>

<!-- vars for javascript -->
<%= javascript_tag do %>
    statuses = <%= raw @js_res.to_json %>;
    total = <%= raw @total.to_json %>;
<% end %>

<div class="row-fluid gray-header">
  <div class="span3"><h2>Dashboard</h2></div>
  <div class="span2">
    <div class="large_text"><%= link_to "#{@projects.count} Projects", projects_path %> </div>
  </div>
  <div class="span2">
    <div class="large_text"><%= link_to "#{@analyses.count} Analyses", analyses_path %> </div>
  </div>
  <div class="span2">
    <div class="large_text"><%= @completed_perc %>% Completed</div>
  </div>
  <div class="span2">
    <div class="large_text"><%= @failed_perc %>% Failed</div>
  </div>
</div>

<div class="row-fluid">
  <div class="span12">
    <div class="analysis-container">
      <div class="analysis-content">
        <% if @current %>
        <div class="analysis-header">Current Analysis: <h3><%= link_to(@current.display_name, analysis_path(@current)) %></h3></div>

        <div class="row-fluid pad-top-20">
          <div class="span6">

         <h4 style="text-align:left;">Progress Status</h4>
          <div id="pie" class="pie"></div>
          </div>
          <div class="span6 pad-top-20">

            <p>Project: <%= link_to(@current.project.name, project_path(@current.project)) %></p>
            <p>Start:
              <% unless @current.start_time.nil? %><%= @current.start_time.strftime("%m/%d/%Y %H:%M:%S") %>
              <% end %>
            </p>
            <p><% unless @current.end_time.nil? %>End: <%= @current.end_time.strftime("%m/%d/%Y %H:%M:%S") %><% end %></p>
            <p><% unless @current.end_time.nil? || @current.start_time.nil? %>Duration:  <%= distance_of_time_in_words(@current.start_time, @current.end_time) %> <% end %></p>
            <p>Status: <span class="label <% if @current.status == 'completed' %>label-success<% end %>"><%=@current.status %></span></p>
            <p><span class="badge badge-info"><%= @current.data_points.count %></span> Datapoints</p>
            <p>
              <% if @current.status == 'completed' %>
                  <% fails = @current.data_points.where(status_message: 'datapoint failure').count %>
                  <span class="badge
                  <% if fails > 0 %>badge-warning <% else %>badge-info<% end %>">
                  <% if fails == 0 %>0<% else %> <%= fails %><% end %>
                  </span> Failures
              <% end %>
            </p>
            <div class="row-fluid pad-top-20">
              <div class="span3 offset3">
                <div class="button-container">
                  <%= link_to 'View Analysis', analysis_path(@current), class: "btn btn-mini" %>
                </div>
              </div>
              <div class="span3">
                <div class="button-container">
                  <%= link_to 'Delete Project', project_path(@current.project), method: :delete,
                              data: {confirm: 'Are you sure?'}, class: "btn btn-mini" %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <% else %>
          <p>There are no analyses to display</p>
        <% end %>
      </div>
    </div>
  </div>
</div>



<% @analyses.each_with_index do |res, index| %>
  <% next if index == 0 %>
  <div class="row-fluid">
    <div class="span12">
      <div class="analysis-container">
        <div class="analysis-content">
          <div class="row-fluid">
            <div class="span3">
              <p><h3><%= link_to(res.display_name, analysis_path(res)) %></h3></p>

            </div>
            <div class="span3">
              <p>Project: <%= link_to(res.project.name, project_path(res.project)) %></p>
              <p>Start:<% unless res.start_time.nil? %><%= res.start_time.strftime("%m/%d/%Y %H:%M:%S") %><% end %></p>
              <p>End: <% unless res.end_time.nil? %><%= res.end_time.strftime("%m/%d/%Y %H:%M:%S") %><% end %></p>
              <p>Duration: <%= distance_of_time_in_words(res.start_time, res.end_time) unless res.start_time.nil? || res.end_time.nil? %></p>

            </div>
            <div class="span3">
              <p>Status: <span class="label <% if res.status == 'completed' %>label-success<% end %>"><%=res.status %></span></p>
              <p><span class="badge badge-info"><%= res.data_points.count %></span> Datapoints</p>

              <p>
                <% fails = res.data_points.where(status_message: 'datapoint failure').count %>
                <span class="badge
                <% if fails > 0 %>badge-warning <% else %>badge-info<% end %>">
                <% if fails == 0 %>0<% else %> <%= fails %><% end %>
                </span> Failures
              </p>
            </div>
            <div class="span3">
              <div class="button-container">
                <%= link_to 'View Analysis', analysis_path(res), class: "btn btn-mini" %>
              </div>
              <div class="button-container">
                <%= link_to 'Delete Project', project_path(res.project), method: :delete,
                            data: {confirm: 'Are you sure?'}, class: "btn btn-mini" %>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

  <script type="text/javascript">
      function make_pie_chart(data, cnt) {
          var w = 230,                        //width
                  h = 230,                            //height
                  r = 110,                            //radius
                  radius = 115,                          //to center on svg
                  color = d3.scale.category20();     //builtin range of colors

          var vis = d3.select("#pie")
                  .append("svg:svg")              //create the SVG element inside the <body>
                  .data([data])                   //associate our data with the document
                  .attr("width", w)           //set the width and height of our visualization (these will be attributes of the <svg> tag
                  .attr("height", h)
                  .append("svg:g")                //make a group to hold our pie chart
                  .attr("transform", "translate(" + radius + "," + radius + ")")    //move the center of the pie chart from 0, 0 to radius, radius

          var arc = d3.svg.arc()              //this will create <path> elements for us using arc data
                  .outerRadius(r);

          var pie = d3.layout.pie()           //this will create arc data for us given a list of values
                  .value(function (d) {
                      return d.value;
                  });    //we must tell it out to access the value of each element in our data array

          var arcs = vis.selectAll("g.slice")     //this selects all <g> elements with class slice (there aren't any yet)
                  .data(pie)                          //associate the generated pie data (an array of arcs, each having startAngle, endAngle and value properties)
                  .enter()                            //this will create <g> elements for every "extra" data element that should be associated with a selection. The result is creating a <g> for every object in the data array
                  .append("svg:g")                //create a group to hold each slice (we will have a <path> and a <text> element associated with each slice)
                  .attr("class", "slice");    //allow us to style things in the slices (like text)

          arcs.append("svg:path")
                  .attr("fill", function (d, i) {
                      return color(i);
                  }) //set the color for each slice to be chosen from the color function defined above
                  .attr("d", arc);                                    //this creates the actual SVG path using the associated data (pie) with the arc drawing function

          //arcs.append("svg:text")                                     //add a label to each slice
          //    .attr("transform", function(d) {                    //set the label's origin to the center of the arc
          //      //we have to make sure to set these before calling arc.centroid
          //      d.innerRadius = 0;
          //      d.outerRadius = r;
          //      return "translate(" + arc.centroid(d) + ")";        //this gives us a pair of coordinates like [50, 50]
          //    })
          //    .attr("text-anchor", "middle")                          //center the text on it's origin
          //    .text(function(d, i) { return data[i].label; });        //get the label from our original data array

          var legend = d3.select("#pie").append("svg")
                  .attr("class", "legend")
                  .attr("width", w)
                  .attr("height", 100)
                  .selectAll("g")
                  .data(color.domain().slice())
                  .enter().append("g")
                  .attr("transform", function (d, i) {
                      return "translate(10," + (i * 20 + 20) + ")";
                  });

          legend.append("rect")
                  .attr("width", 18)
                  .attr("height", 18)
                  .style("fill", color);

          legend.append("text")
                  .attr("x", 24)
                  .attr("y", 9)
                  .attr("dy", ".35em")
                  .text(function (d, i) {
                      return data[i].label + " (" + data[i].value + ")";
                  });

          var total = d3.select("#pie").append("svg")
                  .attr("width", w)
                  .attr("height", 20)
                  .attr("class", "total")
          total.append("text")
                  .attr("x", 33)
                  .attr("y", 9)
                  .attr("dy", ".35em")
                  .text(function (d) {
                      return "TOTAL (" + cnt + ")";
                  });
      }

      //call pie_chart function multiple times when page loads
      function addLoadEvent(func) {
          var oldonload = window.onload;
          if (typeof window.onload != 'function') {
              window.onload = func;
          } else {
              window.onload = function () {
                  if (oldonload) {
                      oldonload();
                  }
                  func();
              }
          }
      }

      addLoadEvent(function () {
          //dispatch chart rendering
          data = statuses;
          cnt = total;
          make_pie_chart(data, cnt);

      });
  </script>

server/app/views/pages/status.html.erb
<%
#*******************************************************************************
# OpenStudio(R), Copyright (c) 2008-2016, Alliance for Sustainable Energy, LLC.
# All rights reserved.
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# (1) Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# (2) Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# (3) Neither the name of the copyright holder nor the names of any contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission from the respective party.
#
# (4) Other than as required in clauses (1) and (2), distributions in any form
# of modifications or other derivative works may not use the "OpenStudio"
# trademark, "OS", "os", or any other confusingly similar designation without
# specific prior written permission from Alliance for Sustainable Energy, LLC.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER, THE UNITED STATES
# GOVERNMENT, OR ANY CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#*******************************************************************************
%>

<h2>Status</h2>

<h4>Awake:
  <% if @awake.nil? %> Not set
      <% else %>
      <%= @awake.awake.strftime('%Y-%m-%d %I:%M %p') %>
  <% end %></h4>

<h4>Awake (Delta):
  <% if @awake_delta %>
    <%= @awake_delta %> Minutes
  <% else %>
      Not Set

  <% end %></h4>

<h4>File System:</h4>
<% if @file_systems %>
    <table class="table table-striped">
      <tr>
        <th>Mount Point</th>
        <th>Percent Used</th>
        <th>Free Space (MB)</th>
        <th>Used Space (MB)</th>
        <th>Total Space (MB)</th>
      </tr>
      <% @file_systems.each do |fs| %>
          <tr>
            <td><%= fs[:mount_point] %></td>
            <td><%= fs[:percent_free] %></td>
            <td><%= fs[:mb_free] %></td>
            <td><%= fs[:mb_used] %></td>
            <td><%= fs[:mb_total] %></td>
          </tr>
      <% end %>
    </table>
<% end %>

<h4>Server:</h4>
<% unless @server.nil? %>
    <table class="table table-striped">
      <tr>
        <th>ID</th>
        <th>IP</th>
        <th>Hostname</th>
        <th>Local Hostname</th>
        <th>User</th>
        <th>Cores</th>
        <th>AMI ID</th>
        <th>Instance ID</th>
        <th>Valid</th>
      </tr>
      <tr>
        <td><%= @server.id %></td>
        <td><%= @server.ip_address %></td>
        <td><%= @server.hostname %></td>
        <td><%= @server.local_hostname %></td>
        <td><%= @server.user %></td>
        <td><%= @server.cores %></td>
        <td><%= @server.ami_id %></td>
        <td><%= @server.instance_id %></td>
        <td><%= @server.valid %></td>
      </tr>
    </table>
<% end %>

<h4>Workers: </h4>
<% if @workers.size > 0 %>
    <table class="table table-striped">
      <tr>
        <th>ID</th>
        <th>IP</th>
        <th>Hostname</th>
        <th>Local Hostname</th>
        <th>User</th>
        <th>Cores</th>
        <th>AMI ID</th>
        <th>Instance ID</th>
        <th>Valid</th>
      </tr>
      <% @workers.each do |worker| %>
          <tr>
            <td><%= worker.id %></td>
            <td><%= worker.ip_address %></td>
            <td><%= worker.hostname %></td>
            <td><%= worker.local_hostname %></td>
            <td><%= worker.user %></td>
            <td><%= worker.cores %></td>
            <td><%= worker.ami_id %></td>
            <td><%= worker.instance_id %></td>
            <td><%= worker.valid %></td>
          </tr>
      <% end %>
    </table>
<% end %>