server/config/routes.rb
Rails.application.routes.draw do
  resources :paretos

  resources :data_points, only: [:index] do
    get :status, on: :collection
  end

  resources :analyses, only: [:index] do
    get :status, on: :collection
  end

  resources :compute_nodes

  resources :projects, shallow: true do
    member do
      get :status
    end

    resources :analyses, shallow: true do
      member do
        post :action
        post :upload
        get :stop
        get :status
        get :page_data
        get :analysis_data
        get :download_status
        get :debug_log
        get :new_view
        get :plot_parallelcoordinates
        post :plot_parallelcoordinates
        get :plot_scatter
        get :plot_radar
        get :plot_bar
        get :download_data
        get :download_analysis_zip
        get :download_algorithm_results_zip
        get :dencity

        get :plot_xy_interactive
        post :plot_xy_interactive
      end

      collection do
        get :status
      end

      resources :measures, only: [:show, :index], shallow: true
      resources :paretos, only: [:show, :index, :edit, :update], shallow: true
      resources :variables, only: [:show, :index, :edit, :update], shallow: true do
        collection do
          get :download_metadata
          get :download_variables
          get :metadata

          get :modify
          post :modify
        end
      end

      resources :data_points, shallow: true do
        member do
          get :view_report
          # get :download_reports # TODO: Remove this
          get :dencity

          # Download reports
          post :download_report

          # TODO: Review the end points
          put :run
          post :upload_file
          delete :result_files
        end

        collection do
          post :batch_upload
        end
      end
    end
    # end
  end

  resources :admin, only: [:index] do
    collection do
      get :backup_database
      post :restore_database
    end
  end

  match '/about', to: 'pages#about', via: :get
  match '/status', to: 'pages#status', via: :get

  root to: 'pages#dashboard'
end

server/app/controllers/variables_controller.rb
#*******************************************************************************
# OpenStudio(R), Copyright (c) 2008-2016, Alliance for Sustainable Energy, LLC.
# All rights reserved.
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# (1) Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# (2) Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# (3) Neither the name of the copyright holder nor the names of any contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission from the respective party.
#
# (4) Other than as required in clauses (1) and (2), distributions in any form
# of modifications or other derivative works may not use the "OpenStudio"
# trademark, "OS", "os", or any other confusingly similar designation without
# specific prior written permission from Alliance for Sustainable Energy, LLC.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER, THE UNITED STATES
# GOVERNMENT, OR ANY CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#*******************************************************************************

class VariablesController < ApplicationController
  # GET /variables
  # GET /variables.json
  def index
    @variables = Variable.where(analysis_id: params[:analysis_id], perturbable: true).order_by(name: 1)
    @outputs = Variable.where(analysis_id: params[:analysis_id], output: true).order_by(name: 1)
    @pivots = Variable.where(analysis_id: params[:analysis_id], pivot: true).order_by(name: 1)
    @others = Variable.where(analysis_id: params[:analysis_id], pivot: false, perturbable: false, output: false).order_by(name: 1)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: Variable.get_variable_data_v2(params[:analysis_id]) }
    end
  end

  # GET /variables/1
  # GET /variables/1.json
  def show
    @variable = Variable.find(params[:id])

    # get all the datapoints that have this variable in the set_variable_values
    @dps = DataPoint.exists("set_variable_values.#{@variable.id}" => true)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @variable }
    end
  end

  # GET /variables/new
  # GET /variables/new.json
  def new
    @variable = Variable.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @variable }
    end
  end

  # GET /variables/1/edit
  def edit
    @variable = Variable.find(params[:id])
  end

  # POST /variables
  # POST /variables.json
  def create
    @variable = Variable.new(params[:variable])

    respond_to do |format|
      if @variable.save
        format.html { redirect_to @variable, notice: 'Variable was successfully created.' }
        format.json { render json: @variable, status: :created, location: @variable }
      else
        format.html { render action: 'new' }
        format.json { render json: @variable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /variables/1
  # PUT /variables/1.json
  def update
    @variable = Variable.find(params[:id])

    respond_to do |format|
      if @variable.update_attributes(params[:variable])
        format.html { redirect_to @variable, notice: 'Variable was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @variable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /variables/1
  # DELETE /variables/1.json
  def destroy
    @variable = Variable.find(params[:id])
    @variable.destroy

    respond_to do |format|
      format.html { redirect_to variables_url }
      format.json { head :no_content }
    end
  end

  def download_variables
    analysis = Analysis.find(params[:analysis_id])

    respond_to do |format|
      format.csv do
        write_and_send_input_variables_csv(analysis)
        # redirect_to @analysis, notice: 'CSV not yet supported for downloading variables'
        # write_and_send_csv(@analysis)
      end
      format.rdata do
        write_and_send_input_variables_rdata(analysis)
      end
    end
  end

  # Bulk modify form
  def modify
    @variables = Variable.where(analysis_id: params[:analysis_id]).order_by(name: 1)

    if request.post?
      # TODO: sanitize params
      @variables.each do |var|
        if params[:visualize_ids].include? var.id
          var.visualize = true
        else
          var.visualize = false
        end
        if params[:export_ids].include? var.id
          var.export = true
        else
          var.export = false
        end
        var.save!
      end
    end
  end

  # GET metadata
  # DenCity view
  def metadata
    @variables = Variable.where(:metadata_id.ne => '', :metadata_id.ne => nil).order_by(name: 1)
  end

  def download_metadata
    respond_to do |format|
      format.csv do
        write_and_send_metadata_csv
      end
    end
  end

  protected

  def write_and_send_metadata_csv
    require 'csv'
    variables = Variable.where(:metadata_id.ne => '', :metadata_id.ne => nil)
    filename =  'dencity_metadata.csv'
    csv_string = CSV.generate do |csv|
      csv << %w(name display_name description units datatype user_defined)
      variables.each do |v|
        csv << [v.metadata_id, v.display_name, '', v.units, v.data_type, false]
      end
    end

    send_data csv_string, filename: filename, type: 'text/csv; charset=iso-8859-1; header=present', disposition: 'attachment'
  end

  def write_and_send_input_variables_csv(analysis)
    require 'csv'
    variables = Variable.get_variable_data_v2(analysis)

    filename = "#{analysis.name}_metadata.csv"
    csv_string = CSV.generate do |csv|
      icnt = 0
      variables.each do |dp|
        icnt += 1
        # Write out the header if this is the first datapoint
        csv << dp.keys if icnt == 1
        csv << dp.values
      end
    end

    send_data csv_string, filename: filename, type: 'text/csv; charset=iso-8859-1; header=present', disposition: 'attachment'
  end

  def write_and_send_input_variables_rdata(analysis)
    variables = Variable.get_variable_data_v2(analysis)

    # need to convert array of hash to hash of arrays
    # [{a: 1, b: 2}, {a: 3, b: 4}] to {a: [1,2], b: [3,4]}
    out_hash = variables.each_with_object(Hash.new([])) do |h1, h|
      h1.each { |k, v| h[k] = h[k] + [v] }
    end

    logger.info out_hash

    download_filename = "#{analysis.name}_metadata.RData"
    data_frame_name = 'metadata'

    Rails.logger.info("outhash is #{out_hash}")

    # TODO: move this to a helper method of some sort under /lib/anlaysis/r/...
    require 'rserve/simpler'
    r = Rserve::Simpler.new
    r.command(data_frame_name.to_sym => out_hash.to_dataframe) do
      %{
            temp <- tempfile('rdata', tmpdir="/tmp")
            save('#{data_frame_name}', file = temp)
            Sys.chmod(temp, mode = "0777", use_umask = TRUE)
         }
    end
    tmp_filename = r.converse('temp')

    if File.exist?(tmp_filename)
      send_data File.open(tmp_filename).read, filename: download_filename, type: 'application/rdata; header=present', disposition: 'attachment'
    else
      fail 'could not create R dataframe'
    end

    # Have R delete the file since it will have permissions to delete the file.
    Rails.logger.info "Temp filename is #{tmp_filename}"
    r_command = "file.remove('#{tmp_filename}')"
    Rails.logger.info "R command is #{r_command}"
    if File.exist? tmp_filename
      r.converse(r_command)
    end
  end
end

server/app/views/variables/index.html.erb
<%
#*******************************************************************************
# OpenStudio(R), Copyright (c) 2008-2016, Alliance for Sustainable Energy, LLC.
# All rights reserved.
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# (1) Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# (2) Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# (3) Neither the name of the copyright holder nor the names of any contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission from the respective party.
#
# (4) Other than as required in clauses (1) and (2), distributions in any form
# of modifications or other derivative works may not use the "OpenStudio"
# trademark, "OS", "os", or any other confusingly similar designation without
# specific prior written permission from Alliance for Sustainable Energy, LLC.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER, THE UNITED STATES
# GOVERNMENT, OR ANY CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#*******************************************************************************
%>

<h2>Variables  <%#= link_to @variables.first.analysis, @variables.first.analysis.display_name, analysis_path(@variables.first.analysis) %></h2>

<% if @variables && @variables.first %>
    <%= link_to 'Modify Variables', modify_analysis_variables_path(@variables.first.analysis) %>  |
    <%= link_to 'Download Variables as R Data Frame', download_variables_analysis_variables_path(@variables.first.analysis, format: :rdata) %>  |
    <%= link_to 'Download Variables as CSV', download_variables_analysis_variables_path(@variables.first.analysis, format: :csv) %>   |
    <%= link_to 'JSON', analysis_variables_path(@variables.first.analysis, format: :json) %>
<% end %>

<h2>Pivot Variables</h2>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Display Name</th>
    <th>Name</th>
    <th>Number of Samples</th>
    <th>Thumbnail</th>
  <tr>
  </thead>
  <tbody>
  <% @pivots.each do |v| %>
      <tr>
        <td><%= link_to v.display_name, variable_path(v) %></td>
        <td><%= v.name %></td>
        <% if v.discrete_values_and_weights %>
            <td><%= v.discrete_values_and_weights.size %></td>
        <% elsif v.uncertainty_type && v.analysis.problem && v.analysis.problem['algorithm'] && v.analysis.problem['algorithm']['number_of_samples'] %>
            <td><%= v.analysis.problem['algorithm']['number_of_samples'] %></td>
        <% else %>
            <td></td>
        <% end %>
        <% if v.perturbable && v.preflight_images.first %>
            <td>
              <%= link_to image_tag(v.preflight_images.first.image.url(:thumb)), v.preflight_images.first.image.url(:original), :popup => ['original_image', 'height=700,width=900'] %>
            </td>
        <% else %>
            <td>No image</td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>


<h2>Variables Variables</h2>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Display Name</th>
    <th>Name</th>
    <th>Number of Samples</th>
    <th>Thumbnail</th>
  <tr>
  </thead>
  <tbody>
  <% @variables.each do |v| %>
      <tr>
        <td><%= link_to v.display_name, variable_path(v) %></td>
        <td><%= v.name %></td>
        <% if v.discrete_values_and_weights %>
            <td><%= v.discrete_values_and_weights.size %></td>
        <% elsif v.uncertainty_type && v.analysis.problem && v.analysis.problem['algorithm'] && v.analysis.problem['algorithm']['number_of_samples'] %>
            <td><%= v.analysis.problem['algorithm']['number_of_samples'] %></td>
        <% else %>
            <td></td>
        <% end %>
        <% if v.perturbable && v.preflight_images.first %>
            <td>
              <%= link_to image_tag(v.preflight_images.first.image.url(:thumb)), v.preflight_images.first.image.url(:original), :popup => ['original_image', 'height=700,width=900'] %>
            </td>
        <% else %>
            <td>No image</td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<h2>Output Variables</h2>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Display Name</th>
    <th>Name</th>
    <th>Taxonomy ID</th>
    <th>Units</th>
    <th>Objective Function Index</th>
  <tr>
  </thead>
  <tbody>
  <% @outputs.each do |v| %>
      <tr>
        <td><%= link_to v.display_name, variable_path(v) %></td>
        <td><%= v.name %></td>
        <td><%= v.metadata_id %></td>
        <td><%= v.units %></td>
        <td><%= v['objective_function_index'] %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<h2>Other Variables/Arguments</h2>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Display Name</th>
    <th>Name</th>
    <th>Units</th>
  <tr>
  </thead>
  <tbody>
  <% @others.each do |v| %>
      <tr>
        <td><%= link_to v.display_name, variable_path(v) %></td>
        <td><%= v.name %></td>
        <td><%= v.units %></td>
      </tr>
  <% end %>
  </tbody>
</table>

server/app/views/variables/metadata.html.erb
<%
#*******************************************************************************
# OpenStudio(R), Copyright (c) 2008-2016, Alliance for Sustainable Energy, LLC.
# All rights reserved.
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# (1) Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# (2) Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# (3) Neither the name of the copyright holder nor the names of any contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission from the respective party.
#
# (4) Other than as required in clauses (1) and (2), distributions in any form
# of modifications or other derivative works may not use the "OpenStudio"
# trademark, "OS", "os", or any other confusingly similar designation without
# specific prior written permission from Alliance for Sustainable Energy, LLC.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER, THE UNITED STATES
# GOVERNMENT, OR ANY CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#*******************************************************************************
%>

<h2>DenCity Metadata</h2>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Metadata ID</th>
    <th>Display Name</th>
    <th>Datatype</th>
    <th>Units</th>
  <tr>
  </thead>
  <tbody>
  <% @variables.each do |v| %>
    <tr>
      <td><%= v.metadata_id %></td>
      <td><%= v.display_name %></td>
      <td><%= v.data_type %></td>
      <td><%= v.units %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<div class="save-btn">
  <p>Note: Only SI Units can be used as DenCity metadata.</p>
  <%= link_to "Download DenCity Metadata (csv)", download_metadata_path(format: :csv), class: "btn btn-primary" %>
</div>

server/app/views/variables/modify.html.erb
<%
#*******************************************************************************
# OpenStudio(R), Copyright (c) 2008-2016, Alliance for Sustainable Energy, LLC.
# All rights reserved.
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# (1) Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# (2) Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# (3) Neither the name of the copyright holder nor the names of any contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission from the respective party.
#
# (4) Other than as required in clauses (1) and (2), distributions in any form
# of modifications or other derivative works may not use the "OpenStudio"
# trademark, "OS", "os", or any other confusingly similar designation without
# specific prior written permission from Alliance for Sustainable Energy, LLC.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER, THE UNITED STATES
# GOVERNMENT, OR ANY CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#*******************************************************************************
%>

<h2>Variables</h2>

<%= form_tag modify_analysis_variables_path, :method => :post do |f| %>
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Machine Name</th>
      <th>Display Name</th>
      <th>Measure Name</th>
      <th>Units</th>
      <th>Visualize</th>
      <th>Export</th>
      <th>Actions</th>
    <tr>
    </thead>
    <tbody>
      <% @variables.each do |var| %>
        <tr>
         <td><%= var.name %></td>
         <td><%= var.display_name %></td>
         <td><% if var.measure? %><%= var.measure.display_name %><% end %></td>
         <td><%= var.units %></td>
         <% v_checked = false %>
         <% if var.visualize %>
           <% v_checked = true %>
         <% end %>
          <% e_checked = false %>
          <% if var.export %>
            <% e_checked = true %>
          <% end %>
         <td><%= check_box_tag 'visualize_ids[]', var.id, v_checked %></td>
         <td><%= check_box_tag 'export_ids[]', var.id, e_checked %></td>
         <td><%= link_to "Edit", edit_variable_path(var) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="save-btn">
    <%= submit_tag "Save Changes", class: "btn btn-primary" %>
  </div>
<% end %>

server/app/views/variables/show.html.erb
<%
#*******************************************************************************
# OpenStudio(R), Copyright (c) 2008-2016, Alliance for Sustainable Energy, LLC.
# All rights reserved.
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# (1) Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# (2) Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# (3) Neither the name of the copyright holder nor the names of any contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission from the respective party.
#
# (4) Other than as required in clauses (1) and (2), distributions in any form
# of modifications or other derivative works may not use the "OpenStudio"
# trademark, "OS", "os", or any other confusingly similar designation without
# specific prior written permission from Alliance for Sustainable Energy, LLC.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER, THE UNITED STATES
# GOVERNMENT, OR ANY CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#*******************************************************************************
%>

<div class="row-fluid">
  <div class="span8">
    <h2>Variable Information </h2>
    <%= link_to "Edit", edit_variable_path(@variable), class: "btn btn-primary" %>
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Field Name</th>
        <th>Field Value</th>
      <tr>
      </thead>
      <tbody>
      <% @variable.as_document.each do |k, v| %>
          <tr>
            <td><%= k %></td>
            <td><%= v %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <h2>Datapoints with this Variable</h2>
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Datapoint Name</th>
        <th>Variable Value</th>
      </tr>
      </thead>
      <tbody>
      <% @dps.each do |dp| %>
          <tr>
            <td><%= link_to dp.name, dp %></td>
            <td><%= dp.set_variable_values[@variable.id] %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

  </div>
  <div class="span4">
    <%= link_to(image_tag(@variable.preflight_images.first.image.url(:small)), @variable.preflight_images.first.image.url(:original), :popup => ['original_image', 'height=700,width=900']) unless @variable.preflight_images.first.nil? %>
  </div>
</div>



  